### ISSUE TITLE
Wrong Installinstructions & VersionMix?

### ISSUE THREAD

**Issue by frankis** [doabit/semantic-ui-sass#44]
Hi there, I just trapped into this and I am not confident that everything is as it should be?   

- Your installation instructions in the github page do show this for ruby (on the MasterBranch):
```
gem 'semantic-ui-sass', github: 'doabit/semantic-ui-sass', branch: 'v1.0beta'
```
This basically result in a pretty outdated version.

-  Your latest commit seems to be a day old and show v 1.12.3.   
After correcting the misleading install instruction and fetching the master branch, the compiled css shows v1.11.5.0, bundle list and gemfile.lock shows the same.

```
remote: git://github.com/doabit/semantic-ui-sass.git
  revision: 768abc6bc500125d75cb29b64282b120f13397bf
  branch: master
  specs:
    semantic-ui-sass (1.11.5.0)
```

What am I doing wrong?
